### ISSUE TITLE
Windows?

### ISSUE THREAD

**Issue by Grummiom** [alvatip/Radioactive-nord#1]
how to use on windows?

**Comment by alvatip** [comment]
I did not created them on windows yet, I will work on that :wink:

**Comment by Rehab42** [comment]
has there been any update for windows? I use the standard nordzy-cursores now but i found the this one to use on Linux and really want it for windows.

**Comment by alvatip** [comment]
@Rehab42, 
Sorry for the delay, I will try to make a windows version this week

**Comment by alvatip** [comment]
Windows version is added in the folder "Archive" and in the releases files
