### ISSUE TITLE
Cursors not supported by specific apps.

### ISSUE THREAD

**Issue by Bretwulf** [alvatip/Radioactive-nord#2]
Cursors do not work in some apps. Slack and Telegram desktop clients just use normal cursors.

**Comment by alvatip** [comment]
Hi, I believe they are flatpak applications ? 
If yes, could you try the second line of [this](https://www.reddit.com/r/voidlinux/comments/wnfwy5/some_apps_not_inheriting_mouse_cursor_theme/) solutions ? (Then logout and in)
If this is not the case, are they coming from snapcraft ? or repo ? 

edit: I've also read that this could come from `/usr/share/icons/default/index.theme` in which the `Inheritence=` argument should be the name of the chosen cursor
